stages:
  - build
  - publish

build:
  stage: build
  #image: node:12-slim
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run typecheck
    - yarn run lint
    - yarn run test
    - yarn run build
  tags:
    - nodejs
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  #image: node:12-slim
  tags:
    - nodejs
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish
